# workflow name
name: actions single

# 当有 push 到仓库和外部触发的时候就运行
on: [push, repository_dispatch]

# YQ_TOKEN
# YUQUE_GIT_HEXO
jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@mater

      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      #安装依赖(包含yuque-hexo，此处无需安装) from https://github.com/x-cold/yuque-hexo
      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install yuque-hexo -g
          npm install

      # 此处请勿使用hexo clean&&yuque-hexo（重新构建时无需此命令行）同步语雀文章
      - name: yuque-hexo sync
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN_HEXO_SYNC_GITHUB_ONLINE}} # from: 这里是YUQUE_TOKEN: $不能随意改
        run: |
          hexo clean
          yuque-hexo sync || yuque-hexo sync || yuque-hexo sync  # 用 || 来重试的次数

      # 生成可访问的文档
      - name: hexo generate
        run: |
          hexo g

      # 生成pages且推送到文件仓库 from https://github.com/peaceiris/actions-gh-pages
      - name: Deploy hexo to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }} # 此处为 hexo-deploy-key
          external_repository: czlifetime/czlifetime.github.io
          publish_branch: master
          publish_dir: ./public
          commit_message: deploy githubPage
          # commit_message: ${{ github.event.head_commit.message }}
